# Fuzzel Terminal Launcher Configuration
include=/home/pedronsa/.config/fuzzel/theme.ini

[main]
font=Terminess Nerd Font Mono:size=14
dpi-aware=no
width=45
horizontal-pad=15
vertical-pad=12
inner-pad=8
line-height=22
fields=filename,name,generic
terminal=alacritty

[border]
width=2
radius=0


