###################
### APPLICATIONS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER

# Terminal
bind = $mainMod, Q, exec, $terminal

# File Manager
bind = $mainMod, E, exec, $fileManager

# Application Menu / Launcher
bind = $mainMod, SPACE, exec, $menu

# Browser
bind = $mainMod, B, exec, $browser

# Communications (Discord, Telegram, etc.)
bind = $mainMod, D, exec, $comms

# Reload Waybar
bind = $mainMod, R, exec, $reload_waybar

# Screenshot
bind = $mainMod SHIFT, S, exec, $printSc

# File Manager (alternative)
bind = $mainMod, Y, exec, $fmy

# Clipboard History
bind = $mainMod, V, exec, cliphist list | wofi -dmenu | cliphist decode | wl-copy

# Force Close Application
bind = $mainMod, C, killactive

# Open SDDM
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
