#!/usr/bin/env python3
import json
import os
import string
import subprocess

CONFIG_DIR = os.path.expanduser("~/.config")
THEME_FILE = os.path.join(CONFIG_DIR, "theme.json")

def load_theme():
    if not os.path.exists(THEME_FILE):
        print("Error: theme.json not found!")
        exit(1)
    with open(THEME_FILE, "r") as f:
        return json.load(f)

def generate_css(theme):
    css_content = "/* Auto-generated by apply_theme.py */\n"
    for key, value in theme.items():
        if key not in ["name", "nvim_theme", "nvim_plugin"]:
            css_content += f"@define-color {key} #{value};\n"
    
    with open(os.path.join(CONFIG_DIR, "theme.css"), "w") as f:
        f.write(css_content)

def generate_ini(theme):
    ini_content = "[colors-dark]\n# Auto-generated by apply_theme.py\n"
    ini_content += f"background={theme['background']}\n"
    ini_content += f"foreground={theme['foreground']}\n"
    
    # Map regular colors
    colors = [
        theme['black'], theme['red'], theme['green'], theme['yellow'],
        theme['blue'], theme['magenta'], theme['cyan'], theme['white']
    ]
    
    for i, color in enumerate(colors):
        ini_content += f"regular{i}={color}\n"
        
    # Map bright colors (use muted for bright0/comments)
    bright_colors = [
        theme['muted'], theme['red'], theme['green'], theme['yellow'],
        theme['blue'], theme['magenta'], theme['cyan'], theme['white']
    ]
    
    for i, color in enumerate(bright_colors):
        ini_content += f"bright{i}={color}\n"
        
    with open(os.path.join(CONFIG_DIR, "theme.ini"), "w") as f:
        f.write(ini_content)

def generate_lua(theme):
    lua_content = "-- Auto-generated by apply_theme.py\nreturn {\n"
    for key, value in theme.items():
        if key in ["name", "nvim_theme", "nvim_plugin"]:
            lua_content += f'    {key} = "{value}",\n'
        else:
            lua_content += f'    {key} = "rgba({value}ff)",\n'
    lua_content += "}\n"
    
    with open(os.path.join(CONFIG_DIR, "theme.lua"), "w") as f:
        f.write(lua_content)

def generate_yazi_toml(theme):
    template_path = os.path.join(CONFIG_DIR, "yazi", "theme.toml.template")
    if os.path.exists(template_path):
        with open(template_path, "r") as f:
            template = string.Template(f.read())
        
        # Add hash prefix for TOML template
        theme_hashed = {k: f"#{v}" for k, v in theme.items() if k not in ["name", "nvim_theme"]}
        
        output = template.safe_substitute(theme_hashed)
        
        with open(os.path.join(CONFIG_DIR, "yazi", "theme.toml"), "w") as f:
            f.write(output)

def reload_apps():
    print("Reloading apps...")
    subprocess.run(["hyprctl", "reload"], check=False, capture_output=True)
    subprocess.run(["killall", "-SIGUSR2", "waybar"], check=False, capture_output=True)
    # Wofi reads config on launch, no reload needed.
    # Neovim will read next time it opens, or we can send a signal (harder, leave for next open).
    # Yazi reloads automatically or on next open.
    # Foot needs a reload signal
    subprocess.run(["killall", "-SIGUSR1", "foot"], check=False, capture_output=True)

if __name__ == "__main__":
    theme = load_theme()
    print(f"Applying theme: {theme.get('name', 'unknown')}")
    generate_css(theme)
    generate_ini(theme)
    generate_lua(theme)
    generate_yazi_toml(theme)
    reload_apps()
    print("Theme applied successfully!")
