#!/usr/bin/env python3
import json
import os
import string
import subprocess

CONFIG_DIR = os.path.expanduser("~/.config")
THEME_FILE = os.path.join(CONFIG_DIR, "theme.json")

def load_theme():
    if not os.path.exists(THEME_FILE):
        print("Error: theme.json not found!")
        exit(1)
    with open(THEME_FILE, "r") as f:
        return json.load(f)

def generate_css(theme):
    css_content = "/* Auto-generated by apply_theme.py */\n"
    for key, value in theme.items():
        if key not in ["name", "nvim_theme", "nvim_plugin"]:
            css_content += f"@define-color {key} #{value};\n"
    
    with open(os.path.join(CONFIG_DIR, "theme.css"), "w") as f:
        f.write(css_content)

def generate_ini(theme):
    ini_content = "[colors-dark]\n# Auto-generated by apply_theme.py\n"
    ini_content += f"background={theme['background']}\n"
    ini_content += f"foreground={theme['foreground']}\n"
    
    # Map regular colors
    colors = [
        theme['black'], theme['red'], theme['green'], theme['yellow'],
        theme['blue'], theme['magenta'], theme['cyan'], theme['white']
    ]
    
    for i, color in enumerate(colors):
        ini_content += f"regular{i}={color}\n"
        
    # Map bright colors (use muted for bright0/comments)
    bright_colors = [
        theme['muted'], theme['red'], theme['green'], theme['yellow'],
        theme['blue'], theme['magenta'], theme['cyan'], theme['white']
    ]
    
    for i, color in enumerate(bright_colors):
        ini_content += f"bright{i}={color}\n"
        
    with open(os.path.join(CONFIG_DIR, "theme.ini"), "w") as f:
        f.write(ini_content)

def generate_alacritty_theme(theme):
    alacritty_theme = "# Auto-generated by apply_theme.py\n\n"
    alacritty_theme += "[colors.primary]\n"
    alacritty_theme += f'background = "#{theme["background"]}"\n'
    alacritty_theme += f'foreground = "#{theme["foreground"]}"\n\n'
    
    alacritty_theme += "[colors.normal]\n"
    alacritty_theme += f'black = "#{theme["black"]}"\n'
    alacritty_theme += f'red = "#{theme["red"]}"\n'
    alacritty_theme += f'green = "#{theme["green"]}"\n'
    alacritty_theme += f'yellow = "#{theme["yellow"]}"\n'
    alacritty_theme += f'blue = "#{theme["blue"]}"\n'
    alacritty_theme += f'magenta = "#{theme["magenta"]}"\n'
    alacritty_theme += f'cyan = "#{theme["cyan"]}"\n'
    alacritty_theme += f'white = "#{theme["white"]}"\n\n'
    
    alacritty_theme += "[colors.bright]\n"
    alacritty_theme += f'black = "#{theme["muted"]}"\n' # Use muted for bright0
    alacritty_theme += f'red = "#{theme["red"]}"\n'
    alacritty_theme += f'green = "#{theme["green"]}"\n'
    alacritty_theme += f'yellow = "#{theme["yellow"]}"\n'
    alacritty_theme += f'blue = "#{theme["blue"]}"\n'
    alacritty_theme += f'magenta = "#{theme["magenta"]}"\n'
    alacritty_theme += f'cyan = "#{theme["cyan"]}"\n'
    alacritty_theme += f'white = "#{theme["white"]}"\n'
    
    alacritty_dir = os.path.join(CONFIG_DIR, "alacritty")
    os.makedirs(alacritty_dir, exist_ok=True)
    with open(os.path.join(alacritty_dir, "theme.toml"), "w") as f:
        f.write(alacritty_theme)

def generate_lua(theme):
    lua_content = "-- Auto-generated by apply_theme.py\nreturn {\n"
    for key, value in theme.items():
        if key in ["name", "nvim_theme", "nvim_plugin"]:
            lua_content += f'    {key} = "{value}",\n'
        else:
            lua_content += f'    {key} = "rgba({value}ff)",\n'
    lua_content += "}\n"
    
    with open(os.path.join(CONFIG_DIR, "theme.lua"), "w") as f:
        f.write(lua_content)

def generate_yazi_toml(theme):
    template_path = os.path.join(CONFIG_DIR, "yazi", "theme.toml.template")
    if os.path.exists(template_path):
        with open(template_path, "r") as f:
            template = string.Template(f.read())
        
        # Add hash prefix for TOML template
        theme_hashed = {k: f"#{v}" for k, v in theme.items() if k not in ["name", "nvim_theme"]}
        
        output = template.safe_substitute(theme_hashed)
        
        with open(os.path.join(CONFIG_DIR, "yazi", "theme.toml"), "w") as f:
            f.write(output)

def generate_fuzzel_theme(theme):
    fuzzel_theme = "[colors]\n# Auto-generated by apply_theme.py\n"
    fuzzel_theme += f"background={theme['background']}ff\n"
    fuzzel_theme += f"text={theme['foreground']}ff\n"
    fuzzel_theme += f"match={theme['accent']}ff\n"
    fuzzel_theme += f"selection={theme['muted']}ff\n"
    fuzzel_theme += f"selection-text={theme['foreground']}ff\n"
    fuzzel_theme += f"border={theme['accent']}ff\n"
    
    fuzzel_dir = os.path.join(CONFIG_DIR, "fuzzel")
    os.makedirs(fuzzel_dir, exist_ok=True)
    with open(os.path.join(fuzzel_dir, "theme.ini"), "w") as f:
        f.write(fuzzel_theme)

def generate_dunst_theme(theme):
    template_path = os.path.join(CONFIG_DIR, "dunst", "dunstrc.template")
    if os.path.exists(template_path):
        with open(template_path, "r") as f:
            template = string.Template(f.read())
        
        dunst_vars = {
            "background_hex": f"#{theme['background']}",
            "foreground_hex": f"#{theme['foreground']}",
            "muted_hex": f"#{theme['muted']}",
            "accent_hex": f"#{theme['accent']}",
            "red_hex": f"#{theme['red']}"
        }
        
        output = template.safe_substitute(dunst_vars)
        
        with open(os.path.join(CONFIG_DIR, "dunst", "dunstrc"), "w") as f:
            f.write(output)

def generate_tmux_theme(theme):
    bg = f"#{theme['background']}"
    fg = f"#{theme['foreground']}"
    accent = f"#{theme['accent']}"
    muted = f"#{theme['muted']}"
    
    tmux_theme = "# Auto-generated by apply_theme.py\n"
    tmux_theme += f'set -g status-style "bg={bg},fg={fg}"\n'
    tmux_theme += f'set -g message-style "bg={muted},fg={fg}"\n'
    tmux_theme += f'set -g pane-border-style "fg={muted}"\n'
    tmux_theme += f'set -g pane-active-border-style "fg={accent}"\n\n'
    
    tmux_theme += f'set -g status-left "#[bg={accent},fg={bg},bold] #S #[bg=default,fg=default] "\n'
    tmux_theme += f'set -g status-right "#[fg={muted}] %H:%M:%S #[fg={accent},bg=default]│#[fg={fg}] %Y-%m-%d "\n'
    tmux_theme += f'set -g window-status-current-format "#[bg={muted},fg={fg},bold] #I:#W#F "\n'
    tmux_theme += f'set -g window-status-format "#[fg={muted}] #I:#W#F "\n'
    
    tmux_dir = os.path.join(CONFIG_DIR, "tmux")
    os.makedirs(tmux_dir, exist_ok=True)
    with open(os.path.join(tmux_dir, "theme.conf"), "w") as f:
        f.write(tmux_theme)

def reload_apps():
    print("Reloading apps...")
    subprocess.run(["hyprctl", "reload"], check=False, capture_output=True)
    subprocess.run(["killall", "-SIGUSR2", "waybar"], check=False, capture_output=True)
    # Reload Dunst
    subprocess.run(["dunstctl", "reload"], check=False, capture_output=True)
    # Reload Tmux
    tmux_conf = os.path.expanduser("~/.tmux.conf")
    if os.path.exists(tmux_conf):
        subprocess.run(["tmux", "source-file", tmux_conf], check=False, capture_output=True)

if __name__ == "__main__":
    theme = load_theme()
    print(f"Applying theme: {theme.get('name', 'unknown')}")
    generate_css(theme)
    generate_ini(theme)
    generate_alacritty_theme(theme)
    generate_fuzzel_theme(theme)
    generate_dunst_theme(theme)
    generate_tmux_theme(theme)
    generate_lua(theme)
    generate_yazi_toml(theme)
    reload_apps()
    print("Theme applied successfully!")
