[main]
include=~/.config/theme.ini
shell=zsh
# We will pick a font from the list below, but here is the format:
font=Terminus:size=14
pad=15x15

[cursor]
style=block
blink=no

[mouse]
# Hides the mouse pointer as soon as you start typing
hide-when-typing=yes

[csd]
# Disables client-side decorations (removes titlebars if your Wayland compositor supports it)
preferred=none

