###################
### VARIABLES (generated)
###################

# semantic colors (hex without '#', alpha appended where needed)
$color_background        = rgba(2b3339ff)
$color_foreground        = rgba(d3c6aaff)
$color_accent            = rgba(a7c080ff)
$color_muted_accent      = rgba(4b565cff)
$color_alert             = rgba(e67e80ff)
