###################
### VARIABLES ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = dolphin
$menu = wofi --show drun
$browser = firefox
$comms = discord
$reload_waybar = pkill waybar; waybar &

$printSc = hyprshot -m region --clipboard-only
$uFm = yazi
